my_first_dbt_project:
  target: dev
  outputs:
    dev:
      account: TKYQRIU-MV16541
      database: DEV_DATABASE
      password: "zs9Zg3eARrnT4VB"
      role: ACCOUNTADMIN
      schema: staging
      threads: 1
      type: snowflake
      user: SMPUNGA01
      warehouse: COMPUTE_WH

    # prod:
      # account: TKYQRIU-MV16541
      # database: analytics
      # password: "zs9Zg3eARrnT4VB"
      # role: ACCOUNTADMIN
      # schema: public
      # threads: 8
      # type: snowflake
      # user: SMPUNGA01
      # warehouse: COMPUTE_WH

    # ci:
      # account: TKYQRIU-MV16541
      # database: analytics_{{ env_var('COMPUTE_WH_PR_NUMBER')}}
      # password: "zs9Zg3eARrnT4VB"
      # role: ACCOUNTADMIN
      # schema: public
      # threads: 8
      # type: snowflake
      # user: SMPUNGA01
      # warehouse: COMPUTE_WH